baseURL = "http://example.org/"
languageCode = "en-us"
title = "Josh Anderson Photography"

[permalinks]
  journal = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Journal"
    url = "/journal/"
    weight = 2

[taxonomies]
  category = "category"
  tag = "tags"